language: python

python: '3.7'
dist: xenial

install: pip install -r requirements.txt
script: python publish.py
after_success:
    - mkdir out
    - cp style.css index.html out/

deploy:
  local_dir: out
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  github_token:
    secure: OOnZXI9vr3EsjlkoYwfJfkQi/4OEhCyLR8Vprj+UDNZTAy33mUlZujUgxH4uYp7gQ7Gk1LD3fhh3li0iRhRl9kfNZHuv3idSNP66/ynXTtCRpIH4u2FBiTDFit2c05Ljdhoeu9E70f/SaqDbygabAM/FBO0prJQRCghmlAudrWfA/cyA3iaiVk5RG3YMw0nTnuJf/SduO/tdv1eIKDXs6uEm5avMnbFuowyHQEVIlztj5qQe57xlIKzcpAFHkMqDlNDNIXGYvagjrbWZ/tVPhFd+mXJgez7oG/ucrmZc1qZCzdiomWg/yg0ExvLgglXEDFnKtmLmkB7NA5kK0yMmUf88CylwGOYbcmzwD4bSmZYknwzIlVqONZRvXI48KEOPcAzgP1G/ZCf1zGnR86g36Rg17KBhiF5rQdSjV4fzeK2RCOxYN0W5d7JwtLT7p1V8VB/Nc1N62jM25KODfvdSDVNZN4Gn+eY8KKu8+DzEApYG6N7zvcOIcJZJspjtnBnWgFDi5AONWVa91BMjX9FAifMixYUoLpE+8rSdYaluoJCm8sW9EaiYHRtwTNINa5PdJdwkkxY3su1lvL9CCUY2jtBHtglSZAISYy0zZRw8E3Jd5Dt117Rwu2x23YEz5eiqcYU7vsIERriFZWXkms246NvkfG8KTwax/Ozjdvf2bU4=
